#!/bin/bash

RED='\033[0;91m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

esbcoin-cli stop
rm -rf /usr/local/bin/esbcoin*
rm -rf esbcoin-cli_ubuntu-16.04-x64.tar.bz2
rm -rf .esbcoin/mncache.dat .esbcoin/mnpayments.dat .esbcoin/peers.dat .esbcoin/blocks .esbcoin/chainstate .esbcoin/database

wget https://github.com/BlockchainFor/ESBC2/releases/download/2.0.4.7/esbc-daemon-linux-x86_64-static.tar.gz
tar -xvf esbc-daemon-linux-x86_64-static.tar.gz
sudo chmod -R 755 esbcoin-cli
sudo chmod -R 755 esbcoind
sudo cp -p -r esbcoind /usr/local/bin
sudo cp -p -r esbcoin-cli /usr/local/bin
sleep 10
esbcoind -daemon -reindex

echo -e  "

${YELLOW}Wait full syncgronization${NC} use ${GREEN}"esbcoin-cli getblockcount"${NC}
"
sleep 60

#echo -e  "

#${YELLOW}YOU NEED TO START YOUR MASTERNODE FROM WALLET${NC}
#"
#sleep 60
#echo -e "
#IF YOU DON'T SEE ${GREEN}"Masternode successfully started"${NC} START NOW
#"
#sleep 30
#esbcoin-cli --version
#sleep 2
#while ! /usr/local/bin/esbcoin-cli masternode status | grep -o "Masternode successfully started";do
#/usr/local/bin/esbcoin-cli stop;
#sleep 2;
#/usr/local/bin/esbcoind -daemon;
#sleep 10;
#done
