#!/bin/bash

esbcoin-cli stop
rm -rf /usr/local/bin/esbcoin*
rm -rf esbcoin-cli_ubuntu-16.04-x64.tar.bz2
wget https://github.com/BlockchainFor/ESBC2/releases/download/2.0.4.2/esbcoin-cli_ubuntu-16.04-x64.tar.bz2
tar -xvf esbcoin-cli_ubuntu-16.04-x64.tar.bz2
sudo chmod -R 755 esbcoin-cli
sudo chmod -R 755 esbcoind
sudo cp -p -r esbcoind /usr/local/bin
sudo cp -p -r esbcoin-cli /usr/local/bin
esbcoind -daemon
sleep 10
esbcoin-cli --version
sleep 2
while ! /usr/local/bin/esbcoin-cli masternode status | grep -o "Masternode successfully started";do
/usr/local/bin/esbcoin-cli stop;
sleep 2;
/usr/local/bin/esbcoind -daemon;
sleep 10;
done
