#!/bin/bash

RED='\033[0;91m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

esbcoin-cli stop
echo -e "${GREEN} Stopping ESBC wallet   ${NC}"
sleep 10
rm -rf /usr/local/bin/esbcoin*
rm -rf esbc-daemon-linux-x86_64*

wget https://github.com/BlockchainFor/ESBC2/releases/download/2.1.0.1/esbc-daemon-linux-x86_64-static.tar.gz
tar -xvf esbc-daemon-linux-x86_64-static.tar.gz
sudo chmod -R 755 esbcoin-cli
sudo chmod -R 755 esbcoind
sudo cp -p -r esbcoind /usr/local/bin
sudo cp -p -r esbcoin-cli /usr/local/bin

echo -e "${GREEN} Starting the Server... ${NC}"
esbcoind -daemon
sleep 10
esbcoin-cli getinfo


echo -e  "	

${YELLOW}YOU NEED TO START YOUR MASTERNODE FROM WALLET${NC}	
"	
sleep 60	
echo -e "	
IF YOU DON'T SEE ${GREEN}"Masternode successfully started"${NC} START NOW	
"	
sleep 30	
esbcoin-cli --version	
sleep 2	
while ! /usr/local/bin/esbcoin-cli masternode status | grep -o "Masternode successfully started";do	
/usr/local/bin/esbcoin-cli stop;	
sleep 2;	
/usr/local/bin/esbcoind -daemon;	
sleep 15;	
done
